# Generated by Django 4.1 on 2025-02-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='body_fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='me',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='me',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
