# Generated by Django 4.1 on 2025-02-05 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_me_body_fat_alter_me_height_alter_me_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
